import type { NextPage } from 'next'
import Head from 'next/head'
import { useRecoilState } from 'recoil'
import { globalFilterValueState } from '../frontend/atoms/globalFilterValueAtom'
import useProductsQuery from '../frontend/hooks/products/useProductsQuery'
import { filterProducts } from '../frontend/services/products/filterProducts'
import CoursesTable from '../frontend/components/courses/coursesTable'

const Home: NextPage = () => {
  const query = useProductsQuery('products')
  const [globalFilterValue] = useRecoilState(globalFilterValueState)
  return (
      <div>
        <Head>
          <title>Sistemas III</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="main-container">
          <CoursesTable
            products={filterProducts(query?.data?.products, globalFilterValue)}
          />
        </div>
      </div>
  )
}

export default Home
