import type { NextPage } from 'next'
import Head from 'next/head'
import CardComponent from '../frontend/components/dashboard/Card'
import { Card } from 'primereact/card'
import BarChartCourses from '../frontend/components/dashboard/CourseDashBoard'
import SalesPurchasesDashBoard from '../frontend/components/dashboard/Graph'
import ProductSalesDashBoard from '../frontend/components/dashboard/ProductSalesDashBoard'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sistemas III</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="contenedor-dashboard">
        <CardComponent
          name="Ganancias"
          value="$40.000"
          icon="pi-dollar"
          color="green"
        />
        <CardComponent
          name="Ventas"
          value="+1.300"
          icon="pi-shopping-cart"
          color="red"
        />
        <CardComponent
          name="Alumnos"
          value="+45"
          icon="pi-users"
          color="green"
        />
      </div>
      <div>
        <h2 className='title'>Sales & purchases</h2>
      </div>
      <div className="contenedor-grafico">
        <Card className="card-graph">
          <SalesPurchasesDashBoard
            salesEndpoint={'/dashboards/sales'}
            purchasesEndpoint={'/dashboards/purchases'}
            salesColor={'#42A5F5'}
            purchasesColor={'#FFA726'}
            labels={['October', 'November', 'December', 'January', 'February']}
          />
        </Card>
      </div>
      <div>
        <h2 className='title'>Courses & Products Sales</h2>
      </div>
      <div className="contenedor-grafico">
      <Card className="card-graph">
          <ProductSalesDashBoard
            endpoint={'/dashboards/products-sales'}
            label={'Product Sales'}
            color={'#950A21'}
          />
        </Card>
      <Card className="card-graph">
      <BarChartCourses
          endpoint={'/dashboards/courses'}
          label={'Courses Sales'}
          color={'green'}
        />
      </Card>
      </div>
    </div>
  )
}

export default Home
