import type { NextPage } from 'next'
import Head from 'next/head'
import { Card } from 'primereact/card'

const Home: NextPage = () => {
  const footer = <div><p>+20% <span>La última semana</span></p></div>
  const header = <div><h2>Ganancias (Mensual)</h2></div>
  return (
    <div>
      <Head>
        <title>Sistemas III</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='contenedor-dashboard'>
        <Card className='card-item-dashboard' footer={footer} header={header}>
            <div className='card-body'>
              <h2>$40.000</h2>
              <i className="pi pi-check mr-2" style={ { fontSize: '2em' } }></i>
            </div>
        </Card>
        <Card className='card-item-dashboard'>
            Content
        </Card>
        <Card className='card-item-dashboard'>
            Content
        </Card>
      </div>
    </div>
  )
}

export default Home
