import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { useRecoilState } from 'recoil'
import { globalFilterValueState } from '../frontend/atoms/globalFilterValueAtom'
import StockTable from '../frontend/components/stock/StockTable'
import useStocksQuery from '../frontend/hooks/stock/useStocksQuery'
import { filterStocks } from '../frontend/services/stock/filterStocks'

const Stock: NextPage = () => {
  const query = useStocksQuery('stocks')
  const [globalFilterValue] = useRecoilState(globalFilterValueState)
  return (
    <div>
        <Head>
          <title>Stock</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="main-container">
        <StockTable
          stocks={filterStocks(
            query?.data?.stocks,
            Number(globalFilterValue).valueOf()
          )}
        />
      </div>
    </div>

  )
}

export default Stock
