import { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'
import { useRecoilState } from 'recoil'
import { globalFilterValueState } from '../frontend/atoms/globalFilterValueAtom'
import StoresTable from '../frontend/components/store/StoresTable'
import useStoresQuery from '../frontend/hooks/stores/useStoresQuery'
import { filterStores } from '../frontend/services/stores/filterStores'

const Stores: NextPage = () => {
  const query = useStoresQuery('stores')
  const [globalFilterValue] = useRecoilState(globalFilterValueState)
  return (
    <div>
      <Head>
        <title>Depósitos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main-container">
      <StoresTable stores={filterStores(query.data?.stores, globalFilterValue)} />
      </div>
    </div>
  )
}

export default Stores
