import type { NextPage } from 'next'
import Head from 'next/head'
import { useRecoilState } from 'recoil'
import { StudentsFilterValueState } from '../frontend/atoms/students/filterValueAtom'
import StudentsTable from '../frontend/components/students/StudentsTable'
import useStudentsQuery from '../frontend/hooks/students/useStudentsQuery'
import { filterStudents } from '../frontend/services/students/filterStudents'

const Home: NextPage = () => {
  const query = useStudentsQuery('students')
  const [StudentsFilterValue] = useRecoilState(StudentsFilterValueState)
  return (
    <div>
      <Head>
        <title>Sistemas III</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main-container">
        <StudentsTable
        students={filterStudents(query?.data?.students, StudentsFilterValue)}
        />
      </div>
    </div>
  )
}

export default Home
