import type { NextPage } from 'next'
import Head from 'next/head'
import NavBar from '../components/NavBar'
import Summary from '../components/Summary'
import Table from '../components/Table'
import useProductsQuery from '../hooks/useProductsQuery'

const Home: NextPage = () => {
  const query = useProductsQuery('products')
  return (
    <div>
      <Head>
        <title>Sistemas III</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className="main-container">
        <Summary
          inStock={query?.data?.products?.length}
          noStock={'0'}
          available={query?.data?.products?.length}
        />
        <Table products={query?.data?.products} />
      </div>
    </div>
  )
}

export default Home
