import type { NextPage } from 'next'
import Head from 'next/head'
import 'primereact/resources/themes/lara-light-indigo/theme.css'
import 'primereact/resources/primereact.min.css'
import 'primeicons/primeicons.css'
import NavBar from '../components/NavBar'
import Summary from '../components/Summary'
const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>SistemasIII</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <div className='main-container'>
        <Summary/>
      </div>
    </div>
  )
}

export default Home
